# Generated by Django 4.1.1 on 2022-09-29 13:09

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='id',
        ),
        migrations.AddField(
            model_name='task',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2022, 9, 29, 13, 9, 50, 164674, tzinfo=datetime.timezone.utc), verbose_name=datetime.datetime(2022, 9, 29, 13, 9, 50, 164674, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='task',
            name='metaphor',
            field=models.CharField(default='not available', max_length=100),
        ),
        migrations.AddField(
            model_name='task',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('eab54fa4-ae0f-4fb4-b939-fe50772428dd'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='task',
            name='update_at',
            field=models.DateField(default=datetime.datetime(2022, 9, 29, 13, 9, 50, 164674, tzinfo=datetime.timezone.utc), verbose_name=datetime.datetime(2022, 9, 29, 13, 9, 50, 164674, tzinfo=datetime.timezone.utc)),
        ),
    ]
